{% set name = "pandasgui" %}
{% set version = "0.2.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandasgui-{{ version }}.tar.gz
  sha256: 5b34c2b50269400c2f4ab6b29c77b05f4ba1003887dea95e1b4023ea945b0c6e

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools-git
  run:
    - python
    - appdirs
    - dacite
    - ipython
    - pandas
    - plotly
    # cannot use pip-check b/c pynput needs evdev
    - pynput
    - pyqt >=5

test:
  imports:
    - pandasgui  # [win]
  commands:
    - DISPLAY=localhost: 1.0 xvfb-run -a bash -c 'python -c "import pandasgui"'  # [not win]
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/adamerose/pandasgui
  summary: A GUI for Pandas DataFrames
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - adamerose
    - danschef
